site_name: MiroTalk docs v1.0
site_description: MiroTalk WebRTC documentations
site_author: Miroslav Pejic (miroslav.pejic.85@gmail.com)
copyright: © 2023 MiroTalk, all rights reserved
nav:
  - Home: index.md
  - changelogs: 
    - changelogs: changelogs/changelogs.md
  - coturn:
    - stun-turn: coturn/stun-turn.md
    - installation: coturn/installation.md
  - docs:
    - self-hosting: docs/self-hosting.md
  - license:
    - licensing-options: license/licensing-options.md
  - mirotalk-bro:
    - join-room: mirotalk-bro/join-room.md
    - ngrok: mirotalk-bro/ngrok.md
    - self-hosting: mirotalk-bro/self-hosting.md
  - mirotalk-c2c:
    - join-room: mirotalk-c2c/join-room.md
    - ngrok: mirotalk-c2c/ngrok.md
    - self-hosting: mirotalk-c2c/self-hosting.md
  - mirotalk-p2p:
    - api: mirotalk-p2p/api.md
    - join-room: mirotalk-p2p/join-room.md
    - ngrok: mirotalk-p2p/ngrok.md
    - self-hosting: mirotalk-p2p/self-hosting.md
  - mirotalk-sfu:
    - api: mirotalk-sfu/api.md
    - join-room: mirotalk-sfu/join-room.md
    - ngrok: mirotalk-sfu/ngrok.md
    - self-hosting: mirotalk-sfu/self-hosting.md
  - mirotalk-web:
    - api: mirotalk-web/api.md
    - ngrok: mirotalk-web/ngrok.md
    - self-hosting: mirotalk-web/self-hosting.md
  - ngrok:
    - ngrok: ngrok/ngrok.md
  - nvm:
    - nvm: nvm/nvm.md
theme: readthedocs
